<a href="https://colab.research.google.com/github/ii200400/Tensorflow_Tutorial/blob/master/03%20-%20TensorFlow%20Basic/02_Variable(2_1ver).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 개요

플레이스홀더와 변수의 개념 학습

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf

TensorFlow 2.x selected.


# tf.Variable

그래프를 계산하면서 최적화 할 변수들, 이 값이 바로 신경망을 좌우하는 값들이다.

In [ ]:
# tf.random_normal(a,b): 정규분포에 기반한 a~b사이의 랜덤 값을 반환한다.
W = tf.Variable([[1,1], [2,2], [3,3]])
b = tf.Variable([[2,3], [4,5]])
# W = tf.Variable(tf.random.normal([3, 2]))
# b = tf.Variable(tf.random.normal([2, 1]))

# 입력값과 변수들을 계산할 수식을 작성한다.
def expr(x):
  # 행렬 계산을 수행한다.
  # 이 버전에서는 행렬 계산에서 int형과 float형을 곱할 수 없다. (1.15버전은 가능하다..)
  return tf.matmul(x, W) + b

# 결과

In [ ]:
# 임의의 X 값
x_data = [[1, 2, 3], [4, 5, 6]]
# x_data = tf.constant([[1.1, 2.1, 3.1], [4.1, 5.1, 6.1]])

print("=== x_data ===")
print(x_data)

# 이 셀을 계속 실행시키면 W와 b의 값이 바뀌지 않는다. (1.15버전은 계속 바뀐다.)
print("=== W ===")
print(W)
print("=== b ===")
print(b)
print("=== expr ===")

# 위에서 만든 expr 함수를 사용한다.
print(expr(x_data).numpy())

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 1],
       [2, 2],
       [3, 3]], dtype=int32)>
=== b ===
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>
=== expr ===
[[16 17]
 [36 37]]


# 전체 코드

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf

W = tf.Variable([[1,1], [2,2], [3,3]])
b = tf.Variable([[2,3], [4,5]])

def expr(x):
  return tf.matmul(x, W) + b

# 임의의 X 값
x_data = tf.constant([[1, 2, 3], [4, 5, 6]])
# x_data = tf.constant([[1.1, 2.1, 3.1], [4.1, 5.1, 6.1]])

print("=== x_data ===")
print(x_data)
print("=== W ===")
print(W)
print("=== b ===")
print(b)
print("=== expr ===")

# 위에서 만든 expr 함수를 사용한다.
print(expr(x_data).numpy())